// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1) {
  return window['go']['main']['App']['CreateCollection'](arg1);
}

export function FetchCollections() {
  return window['go']['main']['App']['FetchCollections']();
}

export function FetchConfig() {
  return window['go']['main']['App']['FetchConfig']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}
