// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {config} from '../models';
import {collections} from '../models';

export function CreateCollection(arg1:backend.CreateCollectionRequest):Promise<string>;

export function CreateCollection2(arg1:backend.CreateCollectionRequest):Promise<void>;

export function CreateNewFolder(arg1:string,arg2:string):Promise<void>;

export function FetchCollections():Promise<Array<backend.Collection>>;

export function FetchConfig():Promise<config.Config>;

export function GetCollection(arg1:string):Promise<collections.Collection>;

export function GetCollections(arg1:string):Promise<Array<collections.Collection>>;

export function RenameCollection(arg1:string,arg2:string):Promise<void>;

export function SelectFolder():Promise<string>;

export function SendRequest(arg1:backend.HttpRequest):Promise<string>;
