// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {collections} from '../models';
import {config} from '../models';
import {request} from '../models';

export function CreateCollection(arg1:string,arg2:string):Promise<backend.AppResponse>;

export function CreateNewFolder(arg1:string,arg2:string,arg3:string):Promise<backend.AppResponse>;

export function CreateNewHttpRequest(arg1:collections.CreateNewHttpRequest):Promise<backend.AppResponse>;

export function DeleteCollection(arg1:string):Promise<backend.AppResponse>;

export function DeleteItem(arg1:string,arg2:string):Promise<backend.AppResponse>;

export function FetchConfig():Promise<config.Config>;

export function GetCollection(arg1:string):Promise<collections.Collection>;

export function GetCollections(arg1:string):Promise<Array<collections.Collection>>;

export function RenameCollection(arg1:string,arg2:string):Promise<backend.AppResponse>;

export function SelectFolder():Promise<string>;

export function SendRequest(arg1:request.HttpRequest):Promise<string>;
