// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {config} from '../models';

export function CreateCollection(arg1:backend.CreateCollectionRequest):Promise<string>;

export function FetchCollections():Promise<Array<backend.Collection>>;

export function FetchConfig():Promise<config.Config>;

export function SelectFolder():Promise<string>;

export function SendRequest(arg1:backend.HttpRequest):Promise<string>;
