// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCollection(arg1, arg2) {
  return window['go']['main']['App']['CreateCollection'](arg1, arg2);
}

export function CreateItem(arg1) {
  return window['go']['main']['App']['CreateItem'](arg1);
}

export function CreateNewFolder(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateNewFolder'](arg1, arg2, arg3);
}

export function CreateNewHttpRequest(arg1) {
  return window['go']['main']['App']['CreateNewHttpRequest'](arg1);
}

export function DeleteCollection(arg1) {
  return window['go']['main']['App']['DeleteCollection'](arg1);
}

export function DeleteItem(arg1, arg2) {
  return window['go']['main']['App']['DeleteItem'](arg1, arg2);
}

export function FetchConfig() {
  return window['go']['main']['App']['FetchConfig']();
}

export function GetCollection(arg1) {
  return window['go']['main']['App']['GetCollection'](arg1);
}

export function GetCollections(arg1) {
  return window['go']['main']['App']['GetCollections'](arg1);
}

export function RenameCollection(arg1, arg2) {
  return window['go']['main']['App']['RenameCollection'](arg1, arg2);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}
